name: Quilter.io
favicon: null
layout_spectrum: 1
typography_spectrum: 0.5934479
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#fffeec'
    - '#0057a7'
    - '#009ada'
    - '#000200'
    - '#bbba9c'
  brandStrength: 0.5
  lightness: 1
  saturation: 0.6471536
  rhythmicContrast: 0.632116
purpose: []
